enftun: add support for enftun-keygen
xaptum/enf-services pull request #10
Opened 2020-06-22 18:39 UTC by drbild

This PR 
- upgrades the xaptum/enftun image to enftun version 0.7.2, which includes `enftun-keygen`.
- updates the READMEs to use `enftun-keygen` to provision the keys, instead of the `enfcli`.

I'm opening this as a mergeable PR, but am open to suggestions to further improve the flow.

For example:
- prompting for the username and address (like `enftun-keygen` prompts for the password), instead of requiring them as command line arguments.
- ???

2020-06-22 21:13 UTC, zanebeckwith requested changes
Overall looks good to me. Definitely easier than all the enfcli rigamarole.

Running the container itself to generate its credentials initially felt weird to me, but I think it's just that `enftun-keygen` is still new to me.

2020-06-22 21:13 UTC, zanebeckwith commented on README.md
> +    # Replace <ADDRESS> with the ENF IPv6 address for the container
Can we mention here that `ADDRESS` can also be the address of the network, if we just want a randomly-chosen address in the network?

In real-world situations, I imagine people will want to choose their address. But for testing (e.g. the getting started tutorial), just trying to get a connection up-and-running without caring about the specific address is more likely

2020-06-23 15:04 UTC, drbild commented
> Running the container itself to generate its credentials initially felt weird to me, but I think it's just that `enftun-keygen` is still new to me.

Yeah, we could package `enftun-keygen` in an eponymous image as well.  That wouldn't make it much simpler to run though, just eliminate the `--entrypoint` argument.

I've got some other thoughts for making it simpler
- prompting for username and address, as mentioned above
- modifying the main `entrypoint.sh` script to accept an argument that species to run `enftun-keygen`, instead of `enftun`, eliminating the `--entrypoint` argument

but would rather punt on those a future PR.  The worst complexity right now is the `--volume` and the `--sysctl` arguments.  I don't see a way to get rid of those.  The best I can think of is to have a `docker-compose` file that we ask folks to download (possibly via `wget` or `curl`).

2020-06-23 15:27 UTC, zanebeckwith commented
> would rather punt on those a future PR

Agreed.

This is a significant improvement over the enfcli noise. I think it will take time for us to use this flow (and, maybe non-Xaptum people to do so, too?!?) to see where the pain points are.

2020-06-23 15:27 UTC, zanebeckwith approved these changes

2020-06-23 15:52 UTC, merged