doc suggestions
xaptum/enf-services pull request #4
Opened 2020-04-08 22:04 UTC by glfejer

This still has the enf0.conf changes, which are not needed.

2020-04-08 22:18 UTC, drbild requested changes

2020-04-08 22:18 UTC, drbild commented on enftun/enf0.conf
> -  # dev = "enf0"
This is the default value; no need to uncomment.

2020-04-08 22:18 UTC, drbild commented on enftun/enf0.conf
> -  # port = "443"
This is the default value; no need to uncomment.

2020-04-09 14:23 UTC, zanebeckwith requested changes
Thanks for this improvement, and for sussing out that the published image hadn't been updated since the change to use the enftun-packaged version of the CA cert file!

As David mentioned, no changes to the config are necessary (that was a result of your triaging the published image being old, right? That's now fixed)

Also, would you remove the commit about removing tools from the image, and make sure those changes aren't made to the `Dockerfile`? (Again, I'm guessing those things are artifacts from your testing)

2020-04-09 14:23 UTC, zanebeckwith commented on enftun/README.md
> +- Copy the key files generated using the  [enf-services
To be more explicit, rather than `key files` how about `the private key and certificate`.

2020-04-09 14:23 UTC, zanebeckwith commented on enftun/README.md
> +README](https://github.com/xaptum/enf-services) into `enf0/`
And, how about `...generated using the instructions in [enf...`?

2020-04-09 15:40 UTC, drbild approved these changes

2020-04-09 15:40 UTC, drbild commented
@zanebeckwith 

A separate issue, but I think we should start versioning these images.    Thoughts?

2020-04-09 20:30 UTC, zanebeckwith approved these changes
Good change, and thanks for being the guinea pig!

2020-04-09 20:34 UTC, zanebeckwith commented
@drbild 


> I think we should start versioning these images.

Agreed.

The `enf-apt-mirror` isn't currently versioned, right? So if there's any consistent versioning scheme we want to follow for all these images, we can specify that now.

Do you want to open an issue for adding versioning?

2020-04-09 20:43 UTC, merged