Use versioning of `enftun` and `enf-apt-mirror` images
xaptum/enf-services pull request #6
Opened 2020-04-10 16:44 UTC by zanebeckwith

This PR:
- Adds version tags for `enftun` and `enf-apt-mirror` images (both are now at `1.0.0`)
- Adds some tools to `enftun` that are useful for testing
  - netcat (the fork that supports IPv6), telnet, wget, and curl
- Bumps `enf-demo-server`'s version (which we had already been using) to `1.0.2`

The newest, versioned, images have been pushed to Docker Hub for `enftun` and `enf-demo-server`, **but not for `enf-apt-mirror`**

fixes #5

2020-04-10 17:20 UTC, drbild requested changes
Since these are public images, we should make sure to push a valid 'latest' tag as well. 

Taking `enftun` as the example:

https://hub.docker.com/r/xaptum/enftun/tags

the current 'latest' tag doesn't match the actual latest release (1.0.0).

I think the easiest way to do this is to 
1) Build the image without a tag - 'latest' will be used automatically.
    `docker build -t $(IMG) .`
2) Tag that image with the version.
    `docker tag $(IMG):latest $(IMG):$(VERSION)`
3) Push both the latest and the explicit version:
    `docker push $(IMG):latest; docker push $(IMG):$(VERSION)`

You should test that out though. I might have something wrong with how Docker treats the 'latest' tag.

2020-04-13 13:54 UTC, zanebeckwith commented
Good call, thanks David. I thought the incorrect latest was something I was doing wrong pulling!

I tested your setup above, and it appears to work (after `pull`ing, the `latest` and current version have the same hash). I've updated this branch with those changes

The `enf-apt-mirror` is currently still not `push`ed by the `Makefile` (the `push` target just echoes); do you want me to update that to actually push?

2020-04-13 16:20 UTC, drbild commented
> The `enf-apt-mirror` is currently still not `push`ed by the `Makefile` (the `push` target just echoes); do you want me to update that to actually push?

Yes please!

2020-04-13 16:21 UTC, drbild approved these changes
LGTM.

2020-04-13 17:19 UTC, zanebeckwith commented
I updated this branch to actually push the `enf-apt-mirror` image(s) in the Makefile (and I pushed them).

2020-04-13 17:19 UTC, merged